Story_5/urls.py
from django.urls import path, include
from .views import matkul, daftar_matkul, hapus

urlpatterns = [
    path('',matkul),
    path('daftar/',daftar_matkul, name='daftar'),
    path('delete/<id_matkul>/', hapus, name='delete')
]

Story_9/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import login_page, signup_page, logout_page, berhasil

app_name = 'Story_9'

urlpatterns = [
    path('', login_page, name='login'),
    path('signup/', signup_page, name='signup'),
    path('logout/', logout_page, name='logout'),
    path('berhasil/',berhasil, name='berhasil')
] 

cobadjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepageku.urls')),
    path('Story_5/', include('Story_5.urls')),
    path('Story_6/', include('Story_6.urls')),
    path('Story_7/', include('Story_7.urls')),
    path('Story_8/', include('Story_8.urls')),
    path('Story_9/', include('Story_9.urls'))
]

Story_9/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

Story_9/forms.py
from django import forms
from .models import Profile
from django.contrib.auth import get_user_model

User = get_user_model()

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

class SignupForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password_first = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password_again = forms.CharField(label="Confirm password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean(self):
        cleaned_data = self.cleaned_data
        password_one = self.cleaned_data.get('password_first')
        password_two = self.cleaned_data.get('password_again')
        if password_one != password_two:
            raise forms.ValidationError("Passwords don't match")
        return cleaned_data

    def clean_username(self):
        username = self.cleaned_data.get('username')
        qs = User.objects.filter(username=username)
        if qs.exists():
            raise forms.ValidationError("The username you've chosen is unavailable.")
        return username

    def clean_email(self):
        email_address = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email_address)
        if qs.exists():
            raise forms.ValidationError("The email address you've chosen is already signed up.")
        return email_address

Story_9/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib import messages
from .models import Profile
from .forms import LoginForm, SignupForm
 
User = get_user_model()


def login_page(request):
    form = LoginForm(request.POST or None)
    context = {
        'form': form
    }
    print(request.user.is_authenticated)
    if form.is_valid():
        print(form.cleaned_data)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/Story_9/berhasil/')
        else:
            print("error.......")

    return render(request, "login.html", context=context)

def signup_page(request):
    form = SignupForm(request.POST or None)
    context = {
        'form': form,
    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password_first")
        User.objects.create_user(username, email, password)
        messages.success(request, f'Account {username} has been created. Please Log In!')

        
    return render(request, "signup.html", context=context)

def berhasil(request):
    return render(request, "berhasil.html")


def logout_page(request):
    logout(request)
    return render(request, 'logout.html')

Story_9/templates/berhasil.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css2?family=Sacramento&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Unna&display=swap" rel="stylesheet">
        <style>
            
        </style>
        <title>Logged in</title>
    </head>
    <body style="text-align: center; background-color: #F3F3F3; margin-top: 200px;">
        <h1 style="font-family: 'Unna', serif; color:#A46643;">Selamat datang, {{ request.user }} !</h1>
        <div>
            <a href="{% url 'Story_9:logout' %}"><button class="btn btn-outline-danger" type="submit">Log out</button></a>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

Story_9/templates/login.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css2?family=Sacramento&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Unna&display=swap" rel="stylesheet">
        
        <style>
            
        </style>
        <title>Log in</title>
    </head>
    <body style="background-color: #F3F3F3; font-family: 'Unna', serif; color:#A46643;">
        <div class="row m-5 justify-content-center">
            <div class="col-md-8 col-sm-8">
                <form method="POST">

                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-info">Login</button>
                </form>
            </div>
        </div>
        <div class="row m-5 justify-content-center">
            <div class="col-md-8 col-sm-8">
                <h5>Don't have an account? <a href="{% url 'Story_9:signup'%}">Sign up</a></h5>
            </div>        
        </div>
        
        <!-- {% if request.user.is_authenticated %}
        <h3>User {{ request.user }} is Logged in</h3>
        {% endif %} -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

Story_9/templates/logout.html
{% load static %}


<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <style>
            .submit {
                margin-top: 15px;
                border: none;
                width: 150px;
                font-size: 20px;
                background-color: #BD5555;
                color: #F3F3F3;
                border-radius: 10px;
            }
            .submit:hover {
                background-color: #920003;
            }
            .container {
                vertical-align: middle;
            }

        </style>
        <title>Log out</title>
    </head>
    <body style="background-color: #F3F3F3;">
    <div class=center>
    <div class="container">
        <div class="row m-5 justify-content-center">
            <div class="col-md-12 col-sm-12 text-center" style="margin-top: 100px;">
                <h1 style="font-family: 'Unna', serif; color:#A46643;">You've logged out</h1>
            </div>
        </div>

        <div class="row m-5 justify-content-center">
            <div class="col-sm-4 text-center">
                <a href="{% url 'Story_9:login' %}"><button class="btn btn-outline-danger" type="submit">Login again</button></a>

            </div>
            <div class="col-sm-4 text-center">
                <a href="/"><button class="btn btn-outline-danger" type="submit">Home</button></a>
            </div>

        </div>
    </div>
    </div>
      
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

Story_9/templates/signup.html
{% load static %}


<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="https://fonts.googleapis.com/css2?family=Sacramento&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Unna&display=swap" rel="stylesheet">
        
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        
        <style>
            
        </style>
        <title>Sign Up</title>
    </head>
    <body style="background-color: #F3F3F3; font-family: 'Unna', serif; color:#A46643; margin-top: -50px;">
        <div class="row m-5 justify-content-center">
            <div class="col text-center">
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <h5 style="color: #A46643;" {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </h5>
                    {% endfor %}
                </ul>
                {% endif %}     
            </div>
        </div>
        
        <div class="row m-5 justify-content-center">
            <div class="col-md-8 col-sm-8">
                <form method="POST">

                    {% csrf_token %}
                
                    {{ form.as_p }}
                
                    <button type="submit" class="btn btn-outline-info">Sign Up</button>
                
                </form>
            </div>        
        </div>
        <div class="row m-5 justify-content-center">
            <div class="col-md-8 col-sm-8">
                <h5 style="color: #A46643">Already have an account? <a href="{% url 'Story_9:login'%}">Log in</a></h5>
            </div>   
        </div>
        


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>